version: '3.4'

services:
  paymentcontrolapi:
    image: paymentcontrolapi
    build:
      context: .
      dockerfile: payment-control-api/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 5198:5198
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      CONNECTIONTRINGS__PAYMENTCONTROLDB: Data Source=App_Data/payment-prod.sqlite
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
